<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SensoryAnalysis.Contracts\SensoryAnalysis.Contracts.csproj" />
    <ProjectReference Include="..\SensoryAnalysis.Services\SensoryAnalysis.Services.csproj" />
  </ItemGroup>

</Project>
