// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensoryAnalysis.Entities;

#nullable disable

namespace SensoryAnalysis.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622221650_AddJudgerCount")]
    partial class AddJudgerCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensoryAnalysis.Entities.Judger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Answer")
                        .HasColumnType("int");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Judgers", (string)null);
                });

            modelBuilder.Entity("SensoryAnalysis.Entities.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JudgerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SampleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JudgerId");

                    b.ToTable("Samples", (string)null);
                });

            modelBuilder.Entity("SensoryAnalysis.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JudgerCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameOfSample1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameOfSample2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Significance")
                        .HasColumnType("int");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("SensoryAnalysis.Entities.Judger", b =>
                {
                    b.HasOne("SensoryAnalysis.Entities.Test", "JudgersTest")
                        .WithMany("Judgers")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JudgersTest");
                });

            modelBuilder.Entity("SensoryAnalysis.Entities.Sample", b =>
                {
                    b.HasOne("SensoryAnalysis.Entities.Judger", "SamplesJudger")
                        .WithMany("Samples")
                        .HasForeignKey("JudgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SamplesJudger");
                });

            modelBuilder.Entity("SensoryAnalysis.Entities.Judger", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SensoryAnalysis.Entities.Test", b =>
                {
                    b.Navigation("Judgers");
                });
#pragma warning restore 612, 618
        }
    }
}
